[package]
name = "rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
better-panic = "^0"
console = "^0.15"
crossterm = "^0.27.0"
once_cell = "^1.18.0"
lazy_static = "^1.4.0"
# chrono = "^0.4"